# Generated by Django 5.2.6 on 2025-10-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chiecouture", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="store_logos/"),
        ),
    ]
